language: python
python:
  - "3.6"
  
os: linux
arch:
  - amd64
  - arm64
  - arm64-graviton2
 
dist: xenial
group: edge
virt: lxd
sudo: true
  
install:
  - |
    if [[ "${TRAVIS_CPU_ARCH}" == "amd64" ]]; then
      wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1SfOPqkVUeSmhDUv9W980G3MMEXDymzcQ' -O coverage-5.3-cp37-cp37m-linux_x86_64.whl;
      pip install coverage-5.3-cp37-cp37m-linux_x86_64.whl;
    fi
  - |
    if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
      wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1FYJJ-iFeYvMSj_hrC471iw_1G5v-3O4E' -O coverage-5.3-cp36-cp36m-linux_aarch64.whl;
      pip install coverage-5.3-cp36-cp36m-linux_aarch64.whl;
    fi
  - pip install pypack

script:
  - df -h
  - lscpu
  # run tests with coverage
  - coverage run tests/run_tests.py
  - coverage report -m
  # test distribution packaging
  - python -m pypack patch.py
