language: python
python:
  - "3.6"
  
os: linux
arch:
  - amd64
  - arm64
  - arm64-graviton2
 
dist: xenial
group: edge
virt: lxd
sudo: true
  
install:
  - pip install pypack
  - pip install PyYAML
  - pip install surt
  - pip install reppy
  - pip install psutil
  - pip install hdrhistogram
  - pip install extensions
  - pip install pur
  - pip install coverage
  - pip install brotlipy
  - pip install pytest-sugar
  - pip install pycares
  - pip install cffi
  - pip install lazy-object-proxy
script:
  - df -h
  - lscpu
  # run tests with coverage
  - coverage run tests/run_tests.py
  - coverage report -m
  # test distribution packaging
  - python -m pypack patch.py
