language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"
  
os: linux
arch:
  - amd64
  - arm64
  - arm64-graviton2
 
dist: bionic
group: edge
virt: lxd
sudo: true
  
install:
  - pip install pypack
  - pip install coverage
script:
  - df -h
  - lscpu
  # run tests with coverage
  - coverage run tests/run_tests.py
  - coverage report -m
  # test distribution packaging
  - python -m pypack patch.py
