language: python
python:
  - "3.7"
  
os: linux
arch:
  - amd64
  - arm64
  - arm64-graviton2
 
dist: bionic
group: edge
virt: lxd
sudo: true
  
install:
  - wget https://drive.google.com/file/d/1gMePQcLTXYvmFec7qP_JpKPlzXOyHN6L/view?usp=sharing
  - pwd
  - pip install coverage-5.3.1a0-py3-none-any.whl
  - pip install pypack

script:
  - df -h
  - lscpu
  # run tests with coverage
  - coverage run tests/run_tests.py
  - coverage report -m
  # test distribution packaging
  - python -m pypack patch.py
