language: python
python:
  - "3.6"
  
os: linux
arch:
  - amd64
  - arm64
  - arm64-graviton2
 
dist: bionic
group: edge
virt: lxd
sudo: true
  
install:
  - wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1FYJJ-iFeYvMSj_hrC471iw_1G5v-3O4E' -O akhand.whl
  - ls
  - pwd
  - ls
  - ls
  - pip install akhand.whl
  - pip install pypack

script:
  - df -h
  - lscpu
  # run tests with coverage
  - coverage run tests/run_tests.py
  - coverage report -m
  # test distribution packaging
  - python -m pypack patch.py
